# Generated by Django 3.2.6 on 2021-08-17 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_hub_auth', '0002_hobbyhubuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbyhubuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
