# Generated by Django 3.2.6 on 2021-08-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_rename_article_articles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
